---
AWSTemplateFormatVersion: '2010-09-09'

Description:
  An S3 bucket configured to serve a git repository as a static website.

Resources:
  WebsiteBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: MyPolicy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'
      Bucket: !Ref WebsiteBucket

  PushToBucketLambda: 
    Type: 'AWS::Lambda::Function'
    Properties: 
      Handler: 'index.handler'
      Role: 
        Fn::GetAtt: 
          - 'LambdaExecutionRole'
          - 'Arn'
      Code: 
        S3Bucket: 'lambda-functions'
        S3Key: 'amilookup.zip'
      Runtime: 'python3.6'
      Timeout: '25'
      TracingConfig:
        Mode: 'Active'

Outputs:
  WebsiteURL:
    Value:
      !GetAtt 'WebsiteBucket.WebsiteURL'
