---
AWSTemplateFormatVersion: '2010-09-09'

Description:
  An S3 bucket to store lambda code.

Resources:

  CodeBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete

Outputs:
  CodeBucket:
    Value: !Ref CodeBucket
    Export:
      Name: !Sub '${AWS::StackName}-codebucket'
  CodeBucketARN:
    Value: !GetAtt 'CodeBucket.Arn'
