FROM amazonlinux:latest

RUN yum -y install python3 \
    python3-pip \
    zip \
    which \
    tar \
    && yum clean all

RUN python3 -m pip install --upgrade pip \
    && python3 -m pip install boto3

RUN ldconfig
RUN export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH